server:
  port: 1989

logging:
  level:
    com.mvc.ethereum: DEBUG
    com.mvc.bitcoincashj: ERROR

mvc:
  env:
    # all property has the preference over any other config bellow.
    all: local
    btc: local
    eth: local
    xrp: local
    bch: local
    ltc: local
    eos: local
    ada: local
    bcx: local
    xlm: local
    neo: local
    iota: local
    xmr: local
    dash: local
    trx: local
    usdt: local
    xem: local
    bnb: local
    etc: local
    ven: local
    xbg: local
    qtum: local
    omg: local
    ont: local
  url:
    eth:
      local: http://127.0.0.1:8545
      test: http://47.254.22.105:8545
      prod: https://mvchain.xyz
  path:
    bch:
      local: 'E:\bitblock\bitcoincashj-blocks\'
      test: '\opt\bitblock\bitcoincashj-blocks\'
      prod: '\opt\bitblock\bitcoincashj-blocks\'
  pass:
    btc:
      local: 123456
      test: 123456
      prod: 123456
    bch:
      local: 123456
      test: 123456
      prod: 123456
  gas:
    eth:
      local:
        limit: 4300000
        price: 22000000000
      test:
        limit: 4300000
        price: 22000000000
      prod:
        limit: 430000
        price: 2200000000

org.ethereum:
#    address: http://192.168.206.229:8545
  address: http://127.0.0.1:8545


cors:
#  allowedOrigin: '*'
  allowedOrigin: '*'

swagger:
  enabled: false
  title: mvc-api-demo
  description: mvc-api-demo
  base-package:  com.mvc.ethereum.controller
  base-path: /**
  exclude-path: /error,/ops/**
  version: @project.version@

trans.log.url: http://rinkeby.etherscan.io/api